import type { Metadata } from "next";
import { Google_Sans_Flex } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ScrollToUp from "@/components/ScrollToUp";
import { ScrollContextProvider } from "@/context/ScrollContext";
import { NotificationsContextProvider } from "@/context/NotificationsContext";
import Footer from "@/components/footer";

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gia Miminoshvili - Full Stack Developer",
  description: "Generated by create next app & Generated by Gia Miminoshvili with ❤️",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSansFlex.variable} antialiased pt-16`}>
        <NotificationsContextProvider>
          <Header />
          <ScrollContextProvider>{children}</ScrollContextProvider>
          <ScrollToUp />
          <Footer />
        </NotificationsContextProvider>
      </body>
    </html>
  );
}
